### ISSUE TITLE
set_nice() only def not use

### ISSUE THREAD

**Issue by imweijh** [Dicklesworthstone/visual_astar_python#1]
first thanks for share this project.
set_nice() function only def not use, os.nice(22) on windows raise a error.

**Comment by Dicklesworthstone** [comment]
Yes, this is designed to run on Ubuntu 22 and higher. But you can comment
that part out to try it on Windows.

**Comment by imweijh** [comment]
`# os.nice(22)`
comment then run success using winpython.
the ffmpeg commands can be successfully executed with w64devkit console.
